name: the_responsive_builder
description: This flutter package provides a set of utilities to aid in building responsive Flutter applications.
version: 1.0.3
repository: https://github.com/ijashuzain/the_responsive_builder

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
